# LWJGL uses native access and sun.misc.Unsafe as part of its supported JNI contract.
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED --sun-misc-unsafe-memory-access=allow
org.gradle.parallel=true
org.gradle.caching=true

project_group=top.ceroxe.rt
project_version=0.1.0
java_version=25
